language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11

    - os: osx
      osx_image: xcode9.3
      env:
        - JAVA_HOME=$(/usr/libexec/java_home)

#    - os: windows  ## Travis-CI does not yet support Java on Windows

cache:
  directories:
    - $HOME/.m2

script: mvn verify
